name: Publish to Public Nuget Feed

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Public Nuget Feed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.1
      with:
        versionSpec: '5.x'

    - name: Determine version
      id: gitversion
      run: echo "##[set-output name=FullSemVer;]$(gitversion /output json /showvariable FullSemVer)"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Pack
      run: dotnet pack --no-build --configuration Release /p:PackageVersion=${{ steps.gitversion.outputs.FullSemVer }}-beta

    - name: Push to NuGet
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}
